replicaCount: 1

image:
  name: servicemesh-full-node
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: "servicemesh-full-node-d"

extraAnnotations:
  app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"servicemesh-full-node-a"}]'
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/scheme: "http"
env:
  - name: JUMPS
    value: "6"
  - name: ID
    value: "D"
  - name: CHAIN_SVC
    value: "http://servicemesh-full-node-a:3000/chain"
  - name: JAEGER_COLLECTOR_ENDPOINT
    value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"

service:
  type: ClusterIP
  port: 3000
route:
  enable: false
  wildcardDomain: ""


extraLabels:
  - app.kubernetes.io/part-of: servicemesh-node
  - app.openshift.io/runtime: nodejs
servicemesh:
  gateway: "servicemesh-node"
  subset: v1