name: Workflow Pipeline
on:
  workflow_dispatch:
    inputs:
      run-unit-tests:
        description: "true/false run unit tests"
        required: false
        type: string
        default: 'false'

permissions: write-all
jobs:
  pipeline-ci:
    name: Pipeline CI
    uses: dacross-org/infra/.github/workflows/pipeline-node.yml@main
    with: 
      project-key: service-mesh-demo
      base-dir: .
      base-href: /
      run-unit-tests: ${{ needs.prepare-environment.outputs.run-unit-tests }}
      docker-tag-prefix: "dev-"
      docker-in-login: true
    secrets:
      docker-in-registry: ${{ secrets.DOCKER_IN_REGISTRY }}
      docker-in-username: ${{ secrets.DOCKER_IN_USER }}
      docker-in-password: ${{ secrets.DOCKER_IN_PASS }}
      docker-out-registry: ${{ secrets.DOCKER_OUT_REGISTRY }}
      docker-out-username: ${{ secrets.DOCKER_OUT_USER }}
      docker-out-password: ${{ secrets.DOCKER_OUT_PASS }}
